### ISSUE TITLE
update AppImage

### ISSUE THREAD

**Issue by orena1** [vg-lab/visimpl#1]
Hi, 
Is it possible to update the AppImage files here:
https://vg-lab.es/visimpl/

I think the version in the AppImage is 0.1.4, the GitHub version is >1

Thanks

**Comment by ptoharia** [comment]
Dear @orena1, thanks for the message. We have to update the ViSimpl's web page. In the meantime, latest AppImages can be found in https://vg-lab.es/apps/visimpl/ Any bug you find please don't hesitate to let us know.

**Comment by orena1** [comment]
Great, thanks!
