### ISSUE TITLE
Example csv file

### ISSUE THREAD

**Issue by orena1** [vg-lab/visimpl#2]
Hi,
Could you please link or upload an example csv file, so that it could be easier to understand what is the expected file-format? even a simple toy example will be great.
Thanks.

**Comment by ptoharia** [comment]
Dear Oren, 

Again, the same problem with the web page not being updated. To see the format of CSVs you could do two things:

- In the latest version (not yet included in the latest AppImages) there is a CLI argument "--testFile" which will create test files and load them. You can afterwards take a look to them.
- In this link you can find very simple examples of csv files: https://vg-lab.es/apps/visimpl/doc/

**Comment by orena1** [comment]
Excellent!
this is helpful, thanks.
